### ISSUE TITLE
rsyslog.conf

### ISSUE THREAD

**Issue by yisany** [kwart/simple-syslog-server#1]
I'm studying your project recently. But I have some problems. 

When using the TLS protocol, it prompted me some errors. I realized I needed to configure rsyslog. conf. Could you show me  this file what you configured?

Thanks

**Comment by kwart** [comment]
You don't need any extra configuration.
Just start the server:
```
java -jar target/simple-syslog-server.jar tls
```
And send a test message over TLS (e.g. use `openssl s_client`):
```
echo "<34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - Test message" | openssl s_client -connect localhost:9898
```
Then you should see the message in the server output:
```
>>> Syslog message came: Rfc5424SyslogEvent [prioVersion=<34>1, facility=4, level=2, version=1, timestamp=2003-10-11T22:14:15.003Z, host=mymachine.example.com, appName=su, procId=-, msgId=ID47, structuredData=-, message=Test message]
```
