### ISSUE TITLE
StringIndexOutOfBoundsException on TCP connection

### ISSUE THREAD

**Issue by bitbythecron** [kwart/simple-syslog-server#18]
Hi I'm trying to get this tool working on my home network. On Laptop 1 (the "syslog server") I clone this project, run `mvn package`, and then from inside the `target` directory, I run:
```
java -jar simple-syslog-server.jar tcp
```
The syslog server starts up (!!!) and I see:
```
Simple syslog server (RFC-5424)
Usage:
  java -jar simple-syslog-server.jar [protocol]

Possible protocols: udp, tcp, tls

Starting Simple Syslog Server
Protocol:     tcp
Bind address: 0.0.0.0
Port:         9898
Creating Syslog server socket
```

From Laptop 2 I run:
```
nc -w0 <laptop1.ip> 9898 <<< "testing again from my home machine"
```

Where, obviously, `<laptop1.ip>` is Laptop 1's local IP address on the home network. As soon as I run that command, from Laptop 1, I see:
```
Handling Syslog client /<laptop2.ip>
Exception in thread "Thread-4" java.lang.StringIndexOutOfBoundsException
  at java.base/java.lang.String.<init>(String.java:615)
  at com.github.kwart.syslog.Rfc5424SyslogEvent.getString(Rfc5424SyslogEvent.java:116)
  at com.github.kwart.syslog.Rfc5424SyslogEvent.<init>(Rfc5424SyslogEvent.java:65)
  at com.github.kwart.syslog.TCPSyslogSocketHandler.handleSyslogMessage(TCPSyslogSocketHandler.java:100)
  at com.github.kwart.syslog.TCPSyslogSocketHandler.run(TCPSyslogSocketHandler.java:75)
  at java.base/java.lang.Thread.run(Thread.java:836)
```

Am I doing anything wrong here? Is that not a valid syslog message? If its is, how can I troubleshoot this some more? Thanks in advance!

**Comment by kwart** [comment]
This is a good question.

The format of messages is specified by the [RFC-5424](https://datatracker.ietf.org/doc/html/rfc5424)

You can either use the `logger` Linux command:

```bash
logger --tcp -n <laptop1.ip> -P 9898 "Test message"
```

or try directly the example message specified in the RFC:

```bash
nc -w0 <laptop1.ip> 9898 <<< "<34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8"
```

I'll also improve the README to cover it.

**Comment by bitbythecron** [comment]
Thank you! I can confirm that the bottom command works for me.
