### ISSUE TITLE
Syslog4j dependency question

### ISSUE THREAD

**Issue by BycorSanchez** [kwart/simple-syslog-server#3]
Hey @kwart 

First of all I would like to thank you. This project has helped me understand how syslog4j library works and save me a ton of time. 

This is not actually an issue, it's rather a background question. I've been reseaching about "org.syslog4j" because the last published version was 10 years ago. Do you know whether is any other recent version or any other library trustworthy to handle syslog servers in java? I've found a lot of repos which contain the original sylog4j source code patched (fixing minor issues) but even these have been many years unmanteined.

Thanks for your time

**Comment by kwart** [comment]
Hi @BycorSanchez, I'm sorry, I don't know about updates or similar projects. This simple wrapper around syslog4j was created mainly for testing Syslog logger in WildFly / JBoss application server.
It was sufficient for our use-case so we didn't need updates.

**Comment by BycorSanchez** [comment]
Thanks for your reply @kwart . I do understand, syslog4j is sufficient as well for my current application but I was just searching for a more reliable and maintained library. Thanks again!

PS: Feel free to close this issue.
